spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prod-db-host:3306/lv2_prod?useSSL=false&serverTimezone=Asia/Seoul
    username: prod_user
    password: prod_password
  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
