name: Dev Deploy

on:
  push:
    branches:
      - dev  # dev 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, dev ]  # self-hosted runner + dev 라벨
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run App
        run: |
          pkill -f lv3-final-mission.jar || true
          nohup java -jar build/libs/lv3-final-mission.jar --spring.profiles.active=dev > app.log 2>&1 &
