name: Dev Deploy

on:
  push:
    branches:
      - dev  # dev 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, dev ]  # self-hosted runner + dev 라벨
    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 디버깅: 현재 작업 경로 확인
      - name: Debug Workspace
        run: |
          echo "Current working directory:"
          pwd
          echo "Files in workspace:"
          ls -al

      # 3️⃣ JDK 21 설정
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 4️⃣ Gradle 실행 권한 부여
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      # 5️⃣ Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build

      # 6️⃣ 앱 실행 (기존 프로세스 종료 후)
      # GitHub Actions 워크플로우 예시
      - name: Run App
        run: |
          export DB_URL=${{ secrets.DEV_DB_URL }}
          export DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}
          export DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}

          pkill -f lv3-final-mission.jar || true
          nohup java -jar build/libs/lv3-final-mission.jar --spring.profiles.active=dev > app.log 2>&1 &
